config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :clearances

  # authenticate :user, ->(user) { user.admin? } do
  # draw :madmin
  # end
  
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'

  authenticate :user, lambda { |u| u.admin? } do
    draw :madmin
    mount Sidekiq::Web => '/sidekiq'

    namespace :madmin do
      resources :impersonates do
        post :impersonate, on: :member
        post :stop_impersonating, on: :collection
      end
    end
  end

  # resources :notifications, only: [:index]

  resources :announcements, only: [:index]

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root to: 'clearances#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/clearance.rb
class Clearance < ApplicationRecord
  validates :degree, :session, :link, presence: true
  belongs_to :user

  enum status: { pending: "Pending", successful: "successful", rejected: "Rejected"}
  enum degree: { "ND Morning": "National Diploma (Morning)", "ND Evening": "National Diploma (Evening)", "HND Morning": "Higher National Diploma (Morning)", "HND Evening": "Higher National Diploma (Evening)" }
end

app/controllers/clearances_controller.rb
class ClearancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_clearance, only: %i[ show edit update destroy ]
  before_action :clearance_limit, only: %i[ new create ]

  # GET /clearances or /clearances.json
  def index
    if !current_user.admin?
      @clearances = current_user.clearances.order(created_at: :desc)
    else
      @clearances = Clearance.all.order(created_at: :desc)
    end
  end

  # GET /clearances/1 or /clearances/1.json
  def show
  end

  # GET /clearances/new
  def new
    @clearance = Clearance.new
  end

  # GET /clearances/1/edit
  def edit
  end

  # POST /clearances or /clearances.json
  def create
    @clearance = current_user.clearances.new(clearance_params)
    if @clearance.save
        redirect_to @clearance, notice: "Your clearance has been submitted successfully and now pending. Kindly remain patient as we work on it. Keep an eye on the notifications icon for updates."
    else
        render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /clearances/1 or /clearances/1.json
  def update
    if @clearance.user == current_user
        if @clearance.update(clearance_params)
            redirect_to @clearance, notice: "Clearance record successfully updated"
        else
            render :edit, status: :unprocessable_entity
        end
    end
  end

  # DELETE /clearances/1 or /clearances/1.json
  def destroy
    if @clearance.user == current_user
        @clearance.destroy
        redirect_to clearances_url, notice: "clearance record successfully deleted"
    else
        redirect_to clearances_path, alert: "You are not authorized"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clearance
      @clearance = Clearance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clearance_params
      params.require(:clearance).permit(:link, :degree, :session)
    end

    def clearance_limit
      @successful_clearance = current_user.clearances.successful
      @pending_clearance = current_user.clearances.pending
      if @successful_clearance.count == 1 && @pending_clearance.count == 1 || @successful_clearance.count == 2 || @pending_clearance.count == 2
        redirect_to clearances_path, alert: "Either one of your two clearances is not rejected yet."
      end
    end
end

app/controllers/madmin/clearances_controller.rb
module Madmin
  class ClearancesController < Madmin::ResourceController
  end
end

app/helpers/clearances_helper.rb
module ClearancesHelper
end

app/views/clearances/_clearance.html.erb
<div id="<%= dom_id clearance %>">
  <p>
    <strong>Link:</strong>
    <%= clearance.link %>
  </p>

  <p>
    <strong>User:</strong>
    <%= clearance.user_id %>
  </p>

  <p>
    <strong>Degree:</strong>
    <%= clearance.degree %>
  </p>

</div>

app/views/clearances/_form.html.erb
<%= form_with(model: clearance) do |form| %>
  <% if clearance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clearance.errors.count, "error") %> prohibited this clearance from being saved:</h2>

      <ul>
      <% clearance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <h6><%= form.label :session, class: 'form-label' %></h6>
    <%= form.text_field :session, class: 'form-control' %>
  </div>

  <div class="my-3">
      <h6><%= form.label :degree, class: "form-label" %></h6>
      <%= form.select :degree, Clearance.degrees.keys.map{ |key| [key.humanize.upcase, key] }, prompt: "Select degree to be cleared", class: "form-select", selected: @clearance.degree %>
  </div>

  <div class="mb-3">
    <h6><%= form.label :link, class: 'form-label' %></h6>
    <%= form.text_field :link, class: 'form-control' %>
  </div>

  <!--<%# <div class="mb-3">
    <%#= form.label :user_id, class: 'form-label' %>
      <%#= form.text_field :user_id, class: 'form-control' %>
  </div>-->

  <!--<div class="mb-3">
    <% if clearance.persisted? %>
      <div class="float-end">
        <%#= link_to 'Destroy', clearance, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>-->

    <%= form.submit class: 'btn btn-primary' %>

    <% if clearance.persisted? %>
      <%= link_to "Cancel", clearance, class: "btn btn-link" %>
    <% else %>
      <%= link_to "Cancel", clearances_path, class: "btn btn-link" %>
    <% end %>
  </div>
<% end %>

app/views/clearances/edit.html.erb
<h1>Edit Clearance</h1>

<%= render 'form', clearance: @clearance %>

app/views/clearances/index.html.erb
<% if current_user.clearances.blank? && !current_user.admin? %>
  <div class="apply text-center">
    <h1>You have not applied for any clearance</h1>
    <%= link_to new_clearance_path, class: 'btn btn-primary' do %>
      Apply now
    <% end %>
  </div>
<% else %>
  <div class="row">
    <div class="col-sm-6">
      <h1>My Clearances</h1>
    </div>

    <div class="col-sm-6 text-end">
    <%= link_to new_clearance_path, class: 'btn btn-primary' do %>
      Add New Clearance
    <% end %>
    </div>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
      

          <th>Link</th>
          <%# <th>User</th> %>
          <th>Degree</th>
          <th>Session</th>
          <% if current_user.admin? %>
            <th>Requested by</th>
          <% end %>
          <th>Status</th>
          <th>Date</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @clearances.each do |clearance| %>
          <%= content_tag :tr, id: dom_id(clearance), class: dom_class(clearance) do %>
            

            <td><%= link_to clearance.link, clearance.link, target: "_blank" %></td>
            <%# <td>= clearance.user</td> %>
            <td><%= clearance.degree.upcase %></td>
            <td><%= clearance.session %></td>
            <% if current_user.admin? %>
              <td><%= clearance.user.name %> (<%= clearance.user.matric_number %>)</td>
            <% end %>
            <% if clearance.status == "pending" %>
              <td><%= link_to clearance.status.capitalize, "#", class: "btn btn-sm btn-primary" %></td>
            <% elsif clearance.status == "successful" %>
              <td><%= link_to clearance.status.capitalize, "#", class: "btn btn-sm btn-success" %></td>
            <% else %>
              <td><%= link_to clearance.status.capitalize, "#", class: "btn btn-sm btn-danger" %></td>
            <% end %>


            <td><%= clearance.created_at.strftime("#{clearance.created_at.day.ordinalize} %B %Y") %></td>
            <td><%= link_to 'Show', clearance %></td>
            
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/clearances/new.html.erb
<h1>New clearance</h1>
<hr>
<div class="row">
    <div class="col-md-4">
        <h4>While applying for a clearance, adhere to the following instructions: </h4>
        <ol>
            <li>Rule 1</li>
            <li>Rule 2</li>
            <li>Rule 3</li>
            <li>Rule 4</li>
        </ol>
    </div>

    <div class="col-md-8">
        <%= render 'form', clearance: @clearance %>
    </div>
</div>

app/views/clearances/show.html.erb
<div class="page-header">
  <%= link_to clearances_path, class: 'btn btn-default' do %>
    My Clearances
  <% end %>
  <%= link_to edit_clearance_path(@clearance), class: 'btn btn-primary btn-sm' do %>
    Edit
  <% end %>
  <h1>
    <%= @clearance.degree.upcase %> (<%= @clearance.session %>)
  </h1>
</div>

<dl class="dl-horizontal">
  <dt>Date submitted:</dt> 
  <dd><%= @clearance.created_at.strftime("#{@clearance.created_at.day.ordinalize} %B %Y") %></dd>
  <hr>
  <dt>
    Status:
    <% if @clearance.status == "pending" %>
      <%= link_to @clearance.status.capitalize, "#", class: "btn btn-sm btn-info" %>
    <% elsif @clearance.status == "successful" %>
      <%= link_to @clearance.status.capitalize, "#", class: "btn btn-sm btn-success" %>
    <% else %>
      <%= link_to @clearance.status.capitalize, "#", class: "btn btn-sm btn-danger" %>
    <% end %>
  </dt>
  <dt>Google Drive Link:</dt>
  <dd><%= link_to @clearance.link %></dd>
  <dt>User:</dt>
  <dd><%= @clearance.user.name %> (<%= @clearance.user.matric_number %>)</dd>
  <dt>Degree:</dt>
  <dd><%= @clearance.degree %></dd>
</dl>